baseurl = "http://ardhyw.github.io/"
languageCode = "en-us"
title = "Catatan"
theme = "hyde-w"
buildDrafts = true
paginate = 10

[author]
    name="ardhyw"

#[permalinks]
#post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    theme = "theme-base-00"
    highlight = "monokai-sublime"
    #defaultDescription = "Noted!"
    #defaultKeywords = ""
    #tagline = "CATATAN"
    dateformat = "2006-01-02"
